name: ${project.name}
version: ${project.version}
author: siwoolol
description: FaraMC Practice Core Plugin made by siwoolol the best man alive
main: lol.siwoo.faramcpracticecore.FaraMCPracticeCore
load: POSTWORLD
website: siwoo.lol

api-version: '1.21'

depend: [ StrikePractice, PlaceholderAPI, ProtocolLib ]
softdepend: [ Luckperms, Multiverse-Core, PlaceholderAPI, ProtocolLib, FastAsyncWorldEdit ]

libraries:
  - org.openjdk.nashorn:nashorn-core:15.4

permissions:
  faramcpracticecore.admin:
    description: "Literally Admin"
    default: op
    children:
      faramcpracticecore.fly: true
  faramcpracticecore.selectarena:
    description: "Allows You To Select Arena"
  faramcpracticecore.fly:
    description: "Allows You To Fly in the Lobby"

commands:
  faraarena:
    usage: "/faraarena <pos1|pos2|corner1|corner2|center> <mapName>"
    description: "Configurator for dynamic arenas (Admin Only)"
    permission: faramcpracticecore.admin
  unrankedgui:
    usage: "/unrankedgui"
    description: "Open the Unranked Queue GUI"
    aliases: ["unranked", "queue"]
  ranked:
    usage: "/ranked"
    description: "Open the Ranked Queue GUI"
  botduel:
    usage: "/botduel"
    description: "Open the PvP Bot GUI"
  duel:
    usage: "/duel <player>"
    description: "Send a duel request to another player"
  duelaccept:
    usage: "/duelaccept <player>"
    description: "Accept a duel request"
  dueldecline:
    usage: "/dueldecline <player>"
    description: "Decline a duel request"
  fly:
    usage: "/fly"
    description: "Allows You To Fly"
  forcewin:
    usage: "/forcewin [round/match]"
    description: "Force Win the Fight/Round (Fight if Unspecified)"
  hurryuppartyowner:
    usage: "/hurryuppartyowner"
    description: "Hurry up party owner black man ahahahhahah"
  suggestgamemodetopartyowner:
    usage: "/suggestgamemodetopartyowner"
    description: "Suggest a Gamemode to Play to the owner of your Party"
  gmc:
    usage: "/gmc"
    description: "Gamemode Creative (Shortcut)"
  gms:
    usage: "/gms"
    description: "Gamemode Survival (Shortcut)"
  gmsp:
    usage: "/gmsp"
    description: "Gamemode Spectator (Shortcut)"
  gma:
    usage: "/gma"
    description: "Gamemode Adventure (Shortcut)"
  sudo:
    usage: "/sudo <target> [command/c:chat]"
  ai:
    usage: "/ai"
    description: "Toggle AI coach mode to improve your PvP skills"
  terms_agree:
    usage: "/terms_agree"
    description: "Agree to the terms of service for FaraMC Practice Core"
  terms_disagree:
    usage: "/terms_disagree"
    description: "Disagree to the terms of service for FaraMC Practice Core"
  train:
    usage: "/train [mode]"
    description: "Access training modes"
  queuelastgame:
    usage: "/queuelastgame"
    description: "Queue the last game that the player has played"